# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\Jordan\Desktop\Unnamed Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\Jordan\Desktop\Unnamed Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Jordan\Desktop\Unnamed Project\CMakeFiles" "C:\Users\Jordan\Desktop\Unnamed Project\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Jordan\Desktop\Unnamed Project\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Build

# Build rule for target.
Build: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Build
.PHONY : Build

# fast build rule for target.
Build/fast:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/build
.PHONY : Build/fast

src/Graphics/Mesh.obj: src/Graphics/Mesh.cpp.obj

.PHONY : src/Graphics/Mesh.obj

# target to build an object file
src/Graphics/Mesh.cpp.obj:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/Graphics/Mesh.cpp.obj
.PHONY : src/Graphics/Mesh.cpp.obj

src/Graphics/Mesh.i: src/Graphics/Mesh.cpp.i

.PHONY : src/Graphics/Mesh.i

# target to preprocess a source file
src/Graphics/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/Graphics/Mesh.cpp.i
.PHONY : src/Graphics/Mesh.cpp.i

src/Graphics/Mesh.s: src/Graphics/Mesh.cpp.s

.PHONY : src/Graphics/Mesh.s

# target to generate assembly for a file
src/Graphics/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/Graphics/Mesh.cpp.s
.PHONY : src/Graphics/Mesh.cpp.s

src/Graphics/Renderer.obj: src/Graphics/Renderer.cpp.obj

.PHONY : src/Graphics/Renderer.obj

# target to build an object file
src/Graphics/Renderer.cpp.obj:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/Graphics/Renderer.cpp.obj
.PHONY : src/Graphics/Renderer.cpp.obj

src/Graphics/Renderer.i: src/Graphics/Renderer.cpp.i

.PHONY : src/Graphics/Renderer.i

# target to preprocess a source file
src/Graphics/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/Graphics/Renderer.cpp.i
.PHONY : src/Graphics/Renderer.cpp.i

src/Graphics/Renderer.s: src/Graphics/Renderer.cpp.s

.PHONY : src/Graphics/Renderer.s

# target to generate assembly for a file
src/Graphics/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/Graphics/Renderer.cpp.s
.PHONY : src/Graphics/Renderer.cpp.s

src/Graphics/ShaderClass.obj: src/Graphics/ShaderClass.cpp.obj

.PHONY : src/Graphics/ShaderClass.obj

# target to build an object file
src/Graphics/ShaderClass.cpp.obj:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/Graphics/ShaderClass.cpp.obj
.PHONY : src/Graphics/ShaderClass.cpp.obj

src/Graphics/ShaderClass.i: src/Graphics/ShaderClass.cpp.i

.PHONY : src/Graphics/ShaderClass.i

# target to preprocess a source file
src/Graphics/ShaderClass.cpp.i:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/Graphics/ShaderClass.cpp.i
.PHONY : src/Graphics/ShaderClass.cpp.i

src/Graphics/ShaderClass.s: src/Graphics/ShaderClass.cpp.s

.PHONY : src/Graphics/ShaderClass.s

# target to generate assembly for a file
src/Graphics/ShaderClass.cpp.s:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/Graphics/ShaderClass.cpp.s
.PHONY : src/Graphics/ShaderClass.cpp.s

src/VectorUtil.obj: src/VectorUtil.cpp.obj

.PHONY : src/VectorUtil.obj

# target to build an object file
src/VectorUtil.cpp.obj:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/VectorUtil.cpp.obj
.PHONY : src/VectorUtil.cpp.obj

src/VectorUtil.i: src/VectorUtil.cpp.i

.PHONY : src/VectorUtil.i

# target to preprocess a source file
src/VectorUtil.cpp.i:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/VectorUtil.cpp.i
.PHONY : src/VectorUtil.cpp.i

src/VectorUtil.s: src/VectorUtil.cpp.s

.PHONY : src/VectorUtil.s

# target to generate assembly for a file
src/VectorUtil.cpp.s:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/VectorUtil.cpp.s
.PHONY : src/VectorUtil.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles\Build.dir\build.make CMakeFiles/Build.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... Build
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... src/Graphics/Mesh.obj
	@echo ... src/Graphics/Mesh.i
	@echo ... src/Graphics/Mesh.s
	@echo ... src/Graphics/Renderer.obj
	@echo ... src/Graphics/Renderer.i
	@echo ... src/Graphics/Renderer.s
	@echo ... src/Graphics/ShaderClass.obj
	@echo ... src/Graphics/ShaderClass.i
	@echo ... src/Graphics/ShaderClass.s
	@echo ... src/VectorUtil.obj
	@echo ... src/VectorUtil.i
	@echo ... src/VectorUtil.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

