# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jayx20/Desktop/Shiny-Barnacle/Shiny-Barnacle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jayx20/Desktop/Shiny-Barnacle/Shiny-Barnacle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jayx20/Desktop/Shiny-Barnacle/Shiny-Barnacle/CMakeFiles /home/jayx20/Desktop/Shiny-Barnacle/Shiny-Barnacle/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jayx20/Desktop/Shiny-Barnacle/Shiny-Barnacle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Build

# Build rule for target.
Build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Build
.PHONY : Build

# fast build rule for target.
Build/fast:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/build
.PHONY : Build/fast

src/Graphics/Mesh.o: src/Graphics/Mesh.cpp.o

.PHONY : src/Graphics/Mesh.o

# target to build an object file
src/Graphics/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/Graphics/Mesh.cpp.o
.PHONY : src/Graphics/Mesh.cpp.o

src/Graphics/Mesh.i: src/Graphics/Mesh.cpp.i

.PHONY : src/Graphics/Mesh.i

# target to preprocess a source file
src/Graphics/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/Graphics/Mesh.cpp.i
.PHONY : src/Graphics/Mesh.cpp.i

src/Graphics/Mesh.s: src/Graphics/Mesh.cpp.s

.PHONY : src/Graphics/Mesh.s

# target to generate assembly for a file
src/Graphics/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/Graphics/Mesh.cpp.s
.PHONY : src/Graphics/Mesh.cpp.s

src/Graphics/Renderer.o: src/Graphics/Renderer.cpp.o

.PHONY : src/Graphics/Renderer.o

# target to build an object file
src/Graphics/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/Graphics/Renderer.cpp.o
.PHONY : src/Graphics/Renderer.cpp.o

src/Graphics/Renderer.i: src/Graphics/Renderer.cpp.i

.PHONY : src/Graphics/Renderer.i

# target to preprocess a source file
src/Graphics/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/Graphics/Renderer.cpp.i
.PHONY : src/Graphics/Renderer.cpp.i

src/Graphics/Renderer.s: src/Graphics/Renderer.cpp.s

.PHONY : src/Graphics/Renderer.s

# target to generate assembly for a file
src/Graphics/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/Graphics/Renderer.cpp.s
.PHONY : src/Graphics/Renderer.cpp.s

src/Graphics/ShaderClass.o: src/Graphics/ShaderClass.cpp.o

.PHONY : src/Graphics/ShaderClass.o

# target to build an object file
src/Graphics/ShaderClass.cpp.o:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/Graphics/ShaderClass.cpp.o
.PHONY : src/Graphics/ShaderClass.cpp.o

src/Graphics/ShaderClass.i: src/Graphics/ShaderClass.cpp.i

.PHONY : src/Graphics/ShaderClass.i

# target to preprocess a source file
src/Graphics/ShaderClass.cpp.i:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/Graphics/ShaderClass.cpp.i
.PHONY : src/Graphics/ShaderClass.cpp.i

src/Graphics/ShaderClass.s: src/Graphics/ShaderClass.cpp.s

.PHONY : src/Graphics/ShaderClass.s

# target to generate assembly for a file
src/Graphics/ShaderClass.cpp.s:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/Graphics/ShaderClass.cpp.s
.PHONY : src/Graphics/ShaderClass.cpp.s

src/VectorUtil.o: src/VectorUtil.cpp.o

.PHONY : src/VectorUtil.o

# target to build an object file
src/VectorUtil.cpp.o:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/VectorUtil.cpp.o
.PHONY : src/VectorUtil.cpp.o

src/VectorUtil.i: src/VectorUtil.cpp.i

.PHONY : src/VectorUtil.i

# target to preprocess a source file
src/VectorUtil.cpp.i:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/VectorUtil.cpp.i
.PHONY : src/VectorUtil.cpp.i

src/VectorUtil.s: src/VectorUtil.cpp.s

.PHONY : src/VectorUtil.s

# target to generate assembly for a file
src/VectorUtil.cpp.s:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/VectorUtil.cpp.s
.PHONY : src/VectorUtil.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Build.dir/build.make CMakeFiles/Build.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Build"
	@echo "... edit_cache"
	@echo "... src/Graphics/Mesh.o"
	@echo "... src/Graphics/Mesh.i"
	@echo "... src/Graphics/Mesh.s"
	@echo "... src/Graphics/Renderer.o"
	@echo "... src/Graphics/Renderer.i"
	@echo "... src/Graphics/Renderer.s"
	@echo "... src/Graphics/ShaderClass.o"
	@echo "... src/Graphics/ShaderClass.i"
	@echo "... src/Graphics/ShaderClass.s"
	@echo "... src/VectorUtil.o"
	@echo "... src/VectorUtil.i"
	@echo "... src/VectorUtil.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

